name: 🐞Bug fix
description: バグ修正を行う
title: "[バグ修正]: "
labels: ["bug"]

body:
  - type: input
    id: what-bug
    attributes:
      label: どのようなバグが発生しているか？
      description: データの送受信が出来ない、ロボットアームが予想外の挙動をしているなど
      placeholder: ex. UIとプラットフォームが通信出来ていない
    validations:
      required: false
  - type: textarea
    id: where-cause
    attributes:
      label: どこに原因がありそう？
      description: データの型が間違っている、ロボットアームの座標系の考え方が間違っているなど
      placeholder: ex. json形式で送受信していると思ったがstr型になっていた
    validations:
      required: false
